""" added base_price

Revision ID: d0e83d76af1a
Revises: 86dbc871ca08
Create Date: 2025-07-24 15:43:51.026569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e83d76af1a'
down_revision: Union[str, Sequence[str], None] = '86dbc871ca08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_logs', sa.Column('base_price', sa.Float(), nullable=True))
    op.add_column('service_types', sa.Column('base_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_types', 'base_price')
    op.drop_column('service_logs', 'base_price')
    # ### end Alembic commands ###
