"""update

Revision ID: 575b59b1c5f0
Revises: cade9abe06ef
Create Date: 2025-07-25 20:04:00.119135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575b59b1c5f0'
down_revision: Union[str, Sequence[str], None] = 'cade9abe06ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_logs', sa.Column('tip', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_logs', 'tip')
    # ### end Alembic commands ###
